### ISSUE TITLE
Consider changing test links

### ISSUE THREAD

**Issue by endearingyoungcharms** [scastillo/not-youtube-dl#5]
maybe change to [this](https://www.youtube.com/watch?v=L9HaNbsIfp0&list=PL6381240952C5486D)

**Comment by Alf0nso** [comment]
I think that would not be a bad Idea

**Comment by hazarek** [comment]
https://www.youtube.com/watch?v=cRinY93UY7o

**Comment by brantje** [comment]
This one is more fitting: https://www.youtube.com/watch?v=SnLB8wysMbY
